name: debezium
lang: java
lang_version: 11
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_build_args: "-Dcloud -Passembly -pl debezium-connector-mysql,debezium-connector-postgres,debezium-connector-sqlserver -am"
  extra_deploy_args: "-Dcloud -Passembly -pl debezium-connector-mysql,debezium-connector-postgres,debezium-connector-sqlserver -am"
  branches:
    - master
    - main
    - /^\d+\.\d+\.x$/
    - /v\d+\.\d+\.\d+\-hotfix\-x/
    - /^gh-readonly-queue.*/