name: debezium
lang: java
lang_version: "11"
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_build_args: "-Dcloud -Passembly -pl debezium-connector-mysql,debezium-connector-postgres,debezium-connector-sqlserver -am"
  extra_deploy_args: "-Dcloud -Passembly -pl debezium-connector-mysql,debezium-connector-postgres,debezium-connector-sqlserver -am"
  branches:
    - master
    - main
    - /^\d+\.\d+\.x$/
    - /^\d+\.\d+\.\d+\.x$/
    - /v\d+\.\d+\.\d+\-hotfix\-x/
    - /v\d+\.\d+\.\d+\-orcl\-hotfix\-x/
    - /^gh-readonly-queue.*/
  tasks:
    - name: create-debezium-tag
      branch: master
      pipeline_file: .semaphore/create-tag.yml
      parameters:
        - name: BRANCH_NAME
          required: true
          description: 'Branch used to create a tag for CP-patched branches (for example 1.9.6.x,1.9.7.x,2.1.0.x). Not intended for v*-hotfix-x branches.'
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent/debezium-core
